---
title: "Logistic Regression Modeling Script"
author: "Ted Zerbe"
date: "December 19, 2022"
---

## Front Matter

```{r, message=FALSE}
# clear environment
rm(list = ls())

# load packages
library(tidyverse)
library(tidymodels)
library(glmnet)
library(doParallel)
```

```{r}
# read in data
training <- read.csv("training.csv")
```

## Data Preparation

```{r, warning=FALSE}
# convert SpinRate to numeric
training <- training %>%
            mutate(SpinRate = as.numeric(SpinRate))
```

```{r}
# convert InPlay to factor
training <- training %>%
            mutate(InPlay = as.factor(InPlay))
```

```{r}
# remove 6 rows with missing values
training <- training %>%
            drop_na()
```

```{r}
# inspect data
glimpse(training)
```

## Modeling

```{r}
# create model specification
logistic_reg_spec <- logistic_reg(penalty = tune(),
                                  mixture = tune()) %>%
                     set_mode("classification") %>%
                     set_engine("glmnet")
logistic_reg_spec

#args(logistic_reg)
```

```{r}
# create model recipe to preprocess data
logistic_reg_rec <- recipe(InPlay ~ ., data = training)

logistic_reg_rec
```

```{r}
# create regular grid of values for tuning
logistic_reg_grid <- grid_regular(penalty(),
                                 mixture(),
                                 levels = 10)
logistic_reg_grid
```

```{r}
# view values in grid
logistic_reg_grid %>% count(penalty) # change hyperparameter to view its tested values
```

```{r}
set.seed(1993)

# create cross-validation folds
folds <- vfold_cv(training, v = 5, strata = InPlay)
glimpse(folds)

# create validation set
val <- validation_split(training, strata = InPlay, prop = 0.80)
glimpse(val)
```

```{r, warning=FALSE}
# create workflow and tune along grid
all_cores <- parallel::detectCores()
cl <- makePSOCKcluster(all_cores)
registerDoParallel(cl)

set.seed(1993)

logistic_reg_wf <- workflow() %>%
                   add_model(logistic_reg_spec) %>%
                   add_recipe(logistic_reg_rec)

logistic_reg_res <- logistic_reg_wf %>%
                    tune_grid(resamples = val, 
                              grid = logistic_reg_grid,
                              control = control_grid(save_pred = TRUE),
                              metrics = metric_set(roc_auc))

stopCluster(cl)
```

```{r}
# collect cv results

# logistic_reg_res %>% collect_predictions()
logistic_reg_res %>% collect_metrics()
logistic_reg_res %>% show_best("roc_auc")

# saveRDS(logistic_reg_res, 'logistic_reg_res.RDS')
```

```{r}
# select best hyperparameters
best_logistic_reg <- logistic_reg_res %>%
                     select_best("roc_auc")
best_logistic_reg
```

```{r}
# visualize model cv performance
logistic_reg_auc <- logistic_reg_res %>%
                    collect_predictions(parameters = best_logistic_reg) %>%
                    roc_curve(InPlay, .pred_0) %>%
                    mutate(model = "Logistic Regression")
autoplot(logistic_reg_auc)
```

```{r}
config <- best_logistic_reg$.config

logistic_reg_metric <- logistic_reg_res %>% collect_metrics()
logistic_reg_metric[logistic_reg_metric$.config == config,]
```

